import type { LedgerData } from "./types";

export const seedData: LedgerData = {
  organizations: [
    { id: "org-northstar", name: "Northstar Mutual", domain: "insurance", notes: "Regional carrier exploring AI-assisted renewal workflows." },
    { id: "org-cascade", name: "Cascade Brokerage Group", domain: "insurance", notes: "Commercial brokerage with strong middle-market access." },
    { id: "org-vector", name: "Vector Reasoning Lab", domain: "ai", notes: "Applied AI product studio focused on agentic workflows." },
    { id: "org-lattice", name: "LatticePoint AI", domain: "ai", notes: "Model operations and evaluation consulting partner." },
    { id: "org-evergreen", name: "Evergreen Home Lending", domain: "mortgage", notes: "Mortgage team interested in borrower education automation." },
    { id: "org-summit", name: "Summit Title & Escrow", domain: "mortgage", notes: "Title partner with real estate referral network." },
    { id: "org-sterling", name: "Sterling & Vale LLP", domain: "legal", notes: "Boutique legal practice advising insurance and technology clients." },
    { id: "org-civic", name: "Civic Counsel Group", domain: "legal", notes: "Policy and compliance advisory group." },
    { id: "org-signal", name: "Signal House Media", domain: "personal-brand", notes: "Executive content and personal brand production team." },
    { id: "org-founder", name: "Founder Field Notes", domain: "personal-brand", notes: "Newsletter and founder audience channel." }
  ],
  contacts: [
    {
      id: "contact-maya",
      name: "Maya Chen",
      title: "VP Commercial Lines",
      organizationId: "org-northstar",
      domain: "insurance",
      email: "maya.chen@northstar.example",
      phone: "(555) 010-1033",
      location: "Seattle, WA",
      relationshipScore: 8,
      strategicValueScore: 9,
      lastInteractionDate: "2026-06-03",
      nextFollowUpDate: "2026-06-04",
      tags: ["renewals", "carrier", "pilot-ready"],
      context: "Strong sponsor for renewal visit copilot. Values operational clarity and defensible ROI."
    },
    {
      id: "contact-darren",
      name: "Darren Price",
      title: "Agency Principal",
      organizationId: "org-cascade",
      domain: "insurance",
      email: "darren.price@cascade.example",
      phone: "(555) 010-2224",
      location: "Portland, OR",
      relationshipScore: 6,
      strategicValueScore: 8,
      lastInteractionDate: "2026-04-18",
      nextFollowUpDate: "2026-06-06",
      tags: ["brokerage", "distribution"],
      context: "Interested but time-constrained. Needs concise demo tied to producer productivity."
    },
    {
      id: "contact-elena",
      name: "Elena Vargas",
      title: "Founder",
      organizationId: "org-vector",
      domain: "ai",
      email: "elena@vector.example",
      phone: "(555) 010-9031",
      location: "San Francisco, CA",
      relationshipScore: 9,
      strategicValueScore: 8,
      lastInteractionDate: "2026-05-29",
      nextFollowUpDate: "2026-06-05",
      tags: ["agent-design", "product"],
      context: "Trusted builder peer. Useful sounding board for ARIS architecture and eval strategy."
    },
    {
      id: "contact-omar",
      name: "Omar Haddad",
      title: "AI Governance Lead",
      organizationId: "org-lattice",
      domain: "ai",
      email: "omar@latticepoint.example",
      phone: "(555) 010-4419",
      location: "Austin, TX",
      relationshipScore: 5,
      strategicValueScore: 7,
      lastInteractionDate: "2026-03-28",
      nextFollowUpDate: "2026-06-04",
      tags: ["governance", "evals", "cold-risk"],
      context: "Valuable but drifting. Reconnect around AI governance patterns for regulated insurance workflows."
    },
    {
      id: "contact-priya",
      name: "Priya Nair",
      title: "Regional Lending Manager",
      organizationId: "org-evergreen",
      domain: "mortgage",
      email: "priya.nair@evergreen.example",
      phone: "(555) 010-7730",
      location: "Bellevue, WA",
      relationshipScore: 7,
      strategicValueScore: 6,
      lastInteractionDate: "2026-05-21",
      nextFollowUpDate: "2026-06-10",
      tags: ["mortgage", "education"],
      context: "Could pilot borrower FAQ automation. Relationship is warm through mutual referral source."
    },
    {
      id: "contact-marcus",
      name: "Marcus Reed",
      title: "Business Development Director",
      organizationId: "org-summit",
      domain: "mortgage",
      email: "marcus@summit.example",
      phone: "(555) 010-1921",
      location: "Tacoma, WA",
      relationshipScore: 4,
      strategicValueScore: 6,
      lastInteractionDate: "2026-02-14",
      nextFollowUpDate: "2026-06-04",
      tags: ["referrals", "cold-risk"],
      context: "Referral network potential, but relationship needs repair and a clear reason to re-engage."
    },
    {
      id: "contact-sophia",
      name: "Sophia Blake",
      title: "Partner",
      organizationId: "org-sterling",
      domain: "legal",
      email: "sophia.blake@sterlingvale.example",
      phone: "(555) 010-7752",
      location: "Los Angeles, CA",
      relationshipScore: 8,
      strategicValueScore: 8,
      lastInteractionDate: "2026-05-31",
      nextFollowUpDate: "2026-06-07",
      tags: ["legal", "insurance-tech"],
      context: "Sharp advisor on liability, contracts, and regulated AI positioning."
    },
    {
      id: "contact-julian",
      name: "Julian Park",
      title: "Policy Counsel",
      organizationId: "org-civic",
      domain: "legal",
      email: "julian@civic.example",
      phone: "(555) 010-3018",
      location: "Washington, DC",
      relationshipScore: 5,
      strategicValueScore: 7,
      lastInteractionDate: "2026-04-03",
      nextFollowUpDate: "2026-06-12",
      tags: ["policy", "compliance"],
      context: "Can help translate ARIS governance into public-sector and compliance language."
    },
    {
      id: "contact-nina",
      name: "Nina Sol",
      title: "Executive Producer",
      organizationId: "org-signal",
      domain: "personal-brand",
      email: "nina@signalhouse.example",
      phone: "(555) 010-6671",
      location: "New York, NY",
      relationshipScore: 7,
      strategicValueScore: 9,
      lastInteractionDate: "2026-06-01",
      nextFollowUpDate: "2026-06-05",
      tags: ["content", "brand", "distribution"],
      context: "Potential partner for Joe's AI and insurance thought leadership pipeline."
    },
    {
      id: "contact-theo",
      name: "Theo Grant",
      title: "Editor",
      organizationId: "org-founder",
      domain: "personal-brand",
      email: "theo@founderfieldnotes.example",
      phone: "(555) 010-8880",
      location: "Chicago, IL",
      relationshipScore: 6,
      strategicValueScore: 6,
      lastInteractionDate: "2026-05-08",
      nextFollowUpDate: "2026-06-09",
      tags: ["newsletter", "founder-audience"],
      context: "May feature ARIS build-in-public story if the angle is crisp and non-promotional."
    }
  ],
  interactions: [
    { id: "int-1", contactId: "contact-maya", date: "2026-06-03", channel: "Video", summary: "Aligned on renewal workflow pain points and pilot success metrics.", sentiment: "positive" },
    { id: "int-2", contactId: "contact-elena", date: "2026-05-29", channel: "Coffee", summary: "Reviewed agent evaluation ideas and human-in-the-loop boundaries.", sentiment: "positive" },
    { id: "int-3", contactId: "contact-nina", date: "2026-06-01", channel: "Call", summary: "Discussed executive command center narrative and content cadence.", sentiment: "positive" },
    { id: "int-4", contactId: "contact-sophia", date: "2026-05-31", channel: "Email", summary: "Sophia offered to review lightweight terms for a pilot agreement.", sentiment: "positive" },
    { id: "int-5", contactId: "contact-omar", date: "2026-03-28", channel: "LinkedIn", summary: "Brief exchange on governance checklists; no concrete follow-up set.", sentiment: "watch" }
  ],
  opportunities: [
    { id: "opp-1", contactId: "contact-maya", title: "Renewal Visit Copilot Pilot", value: "$35K pilot", stage: "Active", probability: 72, nextStep: "Send two-page pilot brief", targetDate: "2026-06-11" },
    { id: "opp-2", contactId: "contact-darren", title: "Producer Intelligence Demo", value: "$18K workshop", stage: "Exploring", probability: 45, nextStep: "Book focused 25-minute demo", targetDate: "2026-06-18" },
    { id: "opp-3", contactId: "contact-nina", title: "Personal Brand Operating System", value: "Strategic distribution", stage: "Active", probability: 64, nextStep: "Share draft content pillars", targetDate: "2026-06-08" },
    { id: "opp-4", contactId: "contact-priya", title: "Borrower Education Assistant", value: "$12K proof of concept", stage: "Signal", probability: 30, nextStep: "Map common borrower questions", targetDate: "2026-06-21" }
  ],
  commitments: [
    { id: "commit-1", contactId: "contact-maya", owner: "Joe", promise: "Send pilot brief with metrics and implementation timeline.", dueDate: "2026-06-04", status: "open" },
    { id: "commit-2", contactId: "contact-sophia", owner: "Contact", promise: "Review pilot terms outline for liability concerns.", dueDate: "2026-06-07", status: "open" },
    { id: "commit-3", contactId: "contact-nina", owner: "Joe", promise: "Send three-positioning angles for ARIS narrative.", dueDate: "2026-06-05", status: "open" }
  ],
  followUpTasks: [
    { id: "task-1", contactId: "contact-maya", title: "Send pilot brief", dueDate: "2026-06-04", status: "open", priority: "High" },
    { id: "task-2", contactId: "contact-omar", title: "Reconnect with governance angle", dueDate: "2026-06-04", status: "open", priority: "Medium" },
    { id: "task-3", contactId: "contact-marcus", title: "Restart referral conversation", dueDate: "2026-06-04", status: "open", priority: "Medium" },
    { id: "task-4", contactId: "contact-nina", title: "Send content pillars", dueDate: "2026-06-05", status: "open", priority: "High" }
  ]
};
